
- name: setup raspooter
  hosts: raspooterhost
  remote_user: pi
  vars:
    ubuntu_image: ubuntu-20.04.2-preinstalled-server-arm64+raspi.img

  tasks:
    - name: Check that the ubuntu_image exists
      shell: "test /tmp/{{ ubuntu_image }}"
      register: IMAGE_EXISTS
      ignore_errors: true    

    - name: download image of ubuntu
      get_url:
        url: https://cdimage.ubuntu.com/releases/20.04.2/release/{{ ubuntu_image }}.xz
        dest: /tmp/{{ ubuntu_image }}.xz
      when: IMAGE_EXISTS.failed == true

    - name: unzip image of ubuntu
      shell: xz --decompress {{ ubuntu_image }}.xz
      args:
        chdir: /tmp
      when: IMAGE_EXISTS.failed == true

    - name: find boot image of ubuntu
      shell: sfdisk -l ubuntu-20.04.2-preinstalled-server-arm64+raspi.img -o Start | sed '0,/^ Start$/d' | sed -n '1p'
      register: START_BOOT
      args:
        chdir: /tmp

    - name: find boot image of ubuntu
      shell: /usr/sbin/sfdisk -l {{ ubuntu_image }} -o Start | sed '0,/^ Start$/d' | sed -n '1p'
      register: START_BOOT
      args:
        executable: /bin/bash
        chdir: /tmp

    - name: find root image of ubuntu
      shell: /usr/sbin/sfdisk -l {{ ubuntu_image }} -o Start | sed '0,/^ Start$/d' | sed -n '2p'
      register: START_ROOT
      args:
        executable: /bin/bash
        chdir: /tmp

    - name: find boot size limit of image of ubuntu
      shell: /usr/sbin/fdisk --bytes -lo Size {{ ubuntu_image }} | sed -n '9p'
      register: BOOT_SIZE_LIMIT
      args:
        executable: /bin/bash
        chdir: /tmp

    - name: find boot size limit of image of ubuntu
      shell: /usr/sbin/fdisk --bytes -lo Size {{ ubuntu_image }} | sed -n '10p'
      register: ROOT_SIZE_LIMIT
      args:
        executable: /bin/bash
        chdir: /tmp
    
    - name: create directory boot_source
      ansible.builtin.file:
        path: /tmp/boot_source
        state: directory
        mode: '0755'

    - name: create directory root_source
      ansible.builtin.file:
        path: /tmp/root_source
        state: directory
        mode: '0755'

    - name: mount boot_source image of ubuntu
      shell: mount {{ ubuntu_image }} -o loop,offset=$(( 512 * {{ START_BOOT.stdout }} )),sizelimit=$(( 1 *  {{ BOOT_SIZE_LIMIT.stdout }} )) /tmp/boot_source/
      become: true
      args:
        executable: /bin/bash
        chdir: /tmp

    - name: mount root_source image of ubuntu
      shell: mount {{ ubuntu_image }} -o loop,offset=$(( 512 * {{ START_ROOT.stdout }} )),sizelimit=$(( 1 *  {{ ROOT_SIZE_LIMIT.stdout }} )) /tmp/root_source/
      become: true
      args:
        executable: /bin/bash
        chdir: /tmp


